"""empty message

Revision ID: 2c5705165115
Revises: 
Create Date: 2025-12-13 12:46:27.206562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5705165115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('Id_Admin', sa.Integer(), nullable=False),
    sa.Column('No_Admin', sa.String(length=100), nullable=False),
    sa.Column('Nr_Telefone', sa.String(length=20), nullable=False),
    sa.Column('No_Email', sa.String(length=100), nullable=False),
    sa.Column('No_Senha', sa.String(length=100), nullable=True),
    sa.Column('Tp_Entrada', sa.String(length=1), nullable=False),
    sa.Column('Fl_Situacao', sa.String(length=1), nullable=False),
    sa.Column('Dt_Cadastro', sa.Date(), nullable=True),
    sa.Column('Hr_Cadastro', sa.DateTime(), nullable=True),
    sa.Column('No_Usualt', sa.String(length=50), nullable=True),
    sa.Column('Dt_Altera', sa.Date(), nullable=True),
    sa.Column('Hr_Altera', sa.DateTime(), nullable=True),
    sa.Column('No_Usudel', sa.String(length=50), nullable=True),
    sa.Column('Dt_Delete', sa.Date(), nullable=True),
    sa.Column('Hr_Delete', sa.DateTime(), nullable=True),
    sa.Column('Fl_Delete', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('Id_Admin'),
    sa.UniqueConstraint('No_Email'),
    sa.UniqueConstraint('No_Senha')
    )
    op.create_table('agendamentos',
    sa.Column('Id_Agendamento', sa.Integer(), nullable=False),
    sa.Column('No_Cliente', sa.String(length=50), nullable=False),
    sa.Column('No_Profissional', sa.String(length=50), nullable=False),
    sa.Column('No_Servico', sa.String(length=50), nullable=False),
    sa.Column('Dt_Agendamento', sa.Date(), nullable=False),
    sa.Column('Hr_Agendamento', sa.Time(), nullable=False),
    sa.Column('Status_agendamento', sa.String(length=20), nullable=True),
    sa.Column('Fl_Situacao', sa.String(length=1), nullable=False),
    sa.Column('Dt_Cadastro', sa.Date(), nullable=True),
    sa.Column('Hr_cadastro', sa.DateTime(), nullable=True),
    sa.Column('No_Usualt', sa.String(length=50), nullable=True),
    sa.Column('Dt_Altera', sa.Date(), nullable=True),
    sa.Column('Hr_Altera', sa.DateTime(), nullable=True),
    sa.Column('No_Usudel', sa.String(length=50), nullable=True),
    sa.Column('Dt_Delete', sa.Date(), nullable=True),
    sa.Column('Hr_Delete', sa.DateTime(), nullable=True),
    sa.Column('Fl_Delete', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('Id_Agendamento')
    )
    op.create_table('clientes',
    sa.Column('Id_Cliente', sa.Integer(), nullable=False),
    sa.Column('No_Cliente', sa.String(length=50), nullable=False),
    sa.Column('Nr_Telefone', sa.String(length=20), nullable=False),
    sa.Column('No_Email', sa.String(length=50), nullable=False),
    sa.Column('No_Senha', sa.String(length=30), nullable=True),
    sa.Column('Tp_Entrada', sa.String(length=1), nullable=False),
    sa.Column('Fl_Situacao', sa.String(length=1), nullable=False),
    sa.Column('Dt_Cadastro', sa.Date(), nullable=True),
    sa.Column('Hr_Cadastro', sa.DateTime(), nullable=True),
    sa.Column('No_Usualt', sa.String(length=50), nullable=True),
    sa.Column('Dt_Altera', sa.Date(), nullable=True),
    sa.Column('Hr_Altera', sa.DateTime(), nullable=True),
    sa.Column('No_Usudel', sa.String(length=50), nullable=True),
    sa.Column('Dt_Delete', sa.Date(), nullable=True),
    sa.Column('Hr_Delete', sa.DateTime(), nullable=True),
    sa.Column('Fl_Delete', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('Id_Cliente'),
    sa.UniqueConstraint('No_Senha')
    )
    op.create_table('profissionais',
    sa.Column('Id_Profissional', sa.Integer(), nullable=False),
    sa.Column('No_Profissional', sa.String(length=50), nullable=False),
    sa.Column('Nr_Telefone', sa.String(length=20), nullable=False),
    sa.Column('No_Email', sa.String(length=100), nullable=False),
    sa.Column('No_Especialidade', sa.String(length=50), nullable=True),
    sa.Column('No_Senha', sa.String(length=50), nullable=True),
    sa.Column('Tp_Entrada', sa.String(length=1), nullable=False),
    sa.Column('Fl_Situacao', sa.String(length=1), nullable=False),
    sa.Column('Dt_Cadastro', sa.Date(), nullable=True),
    sa.Column('Hr_Cadastro', sa.DateTime(), nullable=True),
    sa.Column('No_Usualt', sa.String(length=50), nullable=True),
    sa.Column('Dt_Altera', sa.Date(), nullable=True),
    sa.Column('Hr_Altera', sa.DateTime(), nullable=True),
    sa.Column('No_Usudel', sa.String(length=50), nullable=True),
    sa.Column('Dt_Delete', sa.Date(), nullable=True),
    sa.Column('Hr_Delete', sa.DateTime(), nullable=True),
    sa.Column('Fl_Delete', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('Id_Profissional'),
    sa.UniqueConstraint('No_Email'),
    sa.UniqueConstraint('No_Senha')
    )
    op.create_table('servicos',
    sa.Column('Id_Servico', sa.Integer(), nullable=False),
    sa.Column('No_Servico', sa.String(length=100), nullable=False),
    sa.Column('Pr_Servico', sa.Float(), nullable=False),
    sa.Column('Fl_Situacao', sa.String(length=1), nullable=False),
    sa.Column('Dt_Cadastro', sa.Date(), nullable=True),
    sa.Column('Hr_cadastro', sa.DateTime(), nullable=True),
    sa.Column('No_Usualt', sa.String(length=50), nullable=True),
    sa.Column('Dt_Altera', sa.Date(), nullable=True),
    sa.Column('Hr_Altera', sa.DateTime(), nullable=True),
    sa.Column('No_Usudel', sa.String(length=50), nullable=True),
    sa.Column('Dt_Delete', sa.Date(), nullable=True),
    sa.Column('Hr_Delete', sa.DateTime(), nullable=True),
    sa.Column('Fl_Delete', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('Id_Servico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicos')
    op.drop_table('profissionais')
    op.drop_table('clientes')
    op.drop_table('agendamentos')
    op.drop_table('administrador')
    # ### end Alembic commands ###
