"""mudanca na tabela servico

Revision ID: 3b3851128aef
Revises: fde1cd7658b5
Create Date: 2025-12-23 10:14:04.379667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3851128aef'
down_revision = 'fde1cd7658b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Dc_Descricao1', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('Dc_Descricao2', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('Dc_Descricao3', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('Dc_Descricao4', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_column('Dc_Descricao4')
        batch_op.drop_column('Dc_Descricao3')
        batch_op.drop_column('Dc_Descricao2')
        batch_op.drop_column('Dc_Descricao1')

    # ### end Alembic commands ###
