"""criação de campo na tabela serviços

Revision ID: 4281418283b4
Revises: 2c5705165115
Create Date: 2025-12-13 13:01:56.667360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4281418283b4'
down_revision = '2c5705165115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Tp_Estimado', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_column('Tp_Estimado')

    # ### end Alembic commands ###
