"""atualizacao

Revision ID: 5d8704ecfdba
Revises: 
Create Date: 2025-09-24 22:56:28.395750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d8704ecfdba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    op.drop_table('agendamentos')
    op.drop_table('servicos')
    op.drop_table('profissionais')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.Date(), nullable=True))
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('hora_cadastro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_cadastro', mysql.TIME(), nullable=True))
        batch_op.add_column(sa.Column('data_criacao', sa.DATE(), nullable=True))
        batch_op.drop_column('data')

    op.create_table('profissionais',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('especialidade', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('servicos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('preco', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('agendamentos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('profissional_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('servico_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('hora', mysql.TIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('agendamentos_ibfk_1')),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], name=op.f('agendamentos_ibfk_2')),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], name=op.f('agendamentos_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('clientes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
