"""mudanca na coluna

Revision ID: 706361972873
Revises: 948f2d13783e
Create Date: 2025-09-26 15:17:26.625164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706361972873'
down_revision = '948f2d13783e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('hora_cadastro',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('hora_cadastro',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
