"""mudanca

Revision ID: da3425578cc4
Revises: 728621f16229
Create Date: 2025-09-25 17:19:55.003164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3425578cc4'
down_revision = '728621f16229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('hora_cadastro',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('hora_cadastro',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
