"""mudanca no nome da tabela

Revision ID: dbf0b6b06972
Revises: 4281418283b4
Create Date: 2025-12-15 12:47:43.454164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf0b6b06972'
down_revision = '4281418283b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Nr_Atendimento', sa.String(length=30), nullable=False))
        batch_op.drop_column('No_Email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('No_Email', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('Nr_Atendimento')

    # ### end Alembic commands ###
