"""empty message

Revision ID: edbdd3df5e29
Revises: 
Create Date: 2025-11-20 22:06:08.284659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbdd3df5e29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('Id_admin', sa.Integer(), nullable=False),
    sa.Column('No_admin', sa.String(length=100), nullable=False),
    sa.Column('No_email_admin', sa.String(length=100), nullable=False),
    sa.Column('Nu_tel_admin', sa.String(length=20), nullable=False),
    sa.Column('No_senha_admin', sa.String(length=100), nullable=True),
    sa.Column('Tp_admin', sa.String(length=1), nullable=False),
    sa.Column('At_admin', sa.Integer(), nullable=False),
    sa.Column('Dt_criacao', sa.Date(), nullable=True),
    sa.Column('Hr_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id_admin'),
    sa.UniqueConstraint('No_email_admin'),
    sa.UniqueConstraint('No_senha_admin')
    )
    op.create_table('clientes',
    sa.Column('Id_cliente', sa.Integer(), nullable=False),
    sa.Column('No_cliente', sa.String(length=100), nullable=False),
    sa.Column('No_email_cliente', sa.String(length=100), nullable=False),
    sa.Column('Nu_tel_cliente', sa.String(length=20), nullable=False),
    sa.Column('No_senha_cliente', sa.String(length=100), nullable=True),
    sa.Column('Tp_cliente', sa.String(length=20), nullable=False),
    sa.Column('At_cliente', sa.Integer(), nullable=False),
    sa.Column('Dt_criacao', sa.Date(), nullable=True),
    sa.Column('Hr_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id_cliente'),
    sa.UniqueConstraint('No_email_cliente'),
    sa.UniqueConstraint('No_senha_cliente')
    )
    op.create_table('profissionais',
    sa.Column('Id_profissional', sa.Integer(), nullable=False),
    sa.Column('No_profissional', sa.String(length=100), nullable=False),
    sa.Column('Es_profissional', sa.String(length=100), nullable=True),
    sa.Column('No_email_profissional', sa.String(length=100), nullable=False),
    sa.Column('Nu_tel_profissional', sa.String(length=20), nullable=False),
    sa.Column('No_senha_profissional', sa.String(length=100), nullable=True),
    sa.Column('Tp_profissional', sa.String(length=20), nullable=False),
    sa.Column('At_profissional', sa.Integer(), nullable=False),
    sa.Column('Dt_criacao', sa.Date(), nullable=True),
    sa.Column('Hr_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id_profissional'),
    sa.UniqueConstraint('No_email_profissional'),
    sa.UniqueConstraint('No_senha_profissional')
    )
    op.create_table('servicos',
    sa.Column('Id_servico', sa.Integer(), nullable=False),
    sa.Column('No_servico', sa.String(length=100), nullable=False),
    sa.Column('Pr_servico', sa.Float(), nullable=False),
    sa.Column('At_servico', sa.Integer(), nullable=False),
    sa.Column('Dt_criacao', sa.Date(), nullable=True),
    sa.Column('Hr_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id_servico')
    )
    op.create_table('agendamentos',
    sa.Column('Id_agendamento', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('Dt_agendamento', sa.Date(), nullable=False),
    sa.Column('Hr_agendamento', sa.Time(), nullable=False),
    sa.Column('status_agendamento', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.Id_cliente'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.Id_profissional'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.Id_servico'], ),
    sa.PrimaryKeyConstraint('Id_agendamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamentos')
    op.drop_table('servicos')
    op.drop_table('profissionais')
    op.drop_table('clientes')
    op.drop_table('administrador')
    # ### end Alembic commands ###
