"""mudanca no nome da coluna

Revision ID: fde1cd7658b5
Revises: dbf0b6b06972
Create Date: 2025-12-15 12:51:35.768874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde1cd7658b5'
down_revision = 'dbf0b6b06972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Hr_Atendimento', sa.String(length=30), nullable=False))
        batch_op.drop_column('Nr_Atendimento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Nr_Atendimento', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('Hr_Atendimento')

    # ### end Alembic commands ###
